In [ ]:
import numpy as np
arr = np.random.randint(1, 101, size=(3, 4, 5))
print("Original Array:\n", arr)
mean=arr.mean()
arr[arr > mean] = 0
print("\nArray after replacing elements > mean (", mean, ") with 0:\n", arr)
sum_axis1 = np.sum(arr, axis=1)
print("\nSum along axis=1:\n", sum_axis1)
extracted_columns = arr[:, :, [0, -1]]
print("\nExtracted first and last columns:\n", extracted_columns)


Original Array:
 [[[ 13   1  65  95  79]
  [ 14  19  46  26  64]
  [ 93  18  60  68  48]
  [ 43   7  24  92  46]]

 [[ 58  25  69  56  54]
  [ 59  18  27  86  45]
  [ 81  50   3 100  32]
  [ 31  79  79  27   2]]

 [[ 70  82  44  35  74]
  [ 56  55  50  45  68]
  [ 68  29  33  29  49]
  [  3   9  55  31  90]]]

Array after replacing elements > mean ( 47.95 ) with 0:
 [[[13  1  0  0  0]
  [14 19 46 26  0]
  [ 0 18  0  0  0]
  [43  7 24  0 46]]

 [[ 0 25  0  0  0]
  [ 0 18 27  0 45]
  [ 0  0  3  0 32]
  [31  0  0 27  2]]

 [[ 0  0 44 35  0]
  [ 0  0  0 45  0]
  [ 0 29 33 29  0]
  [ 3  9  0 31  0]]]

Sum along axis=1:
 [[ 70  45  70  26  46]
 [ 31  43  30  27  79]
 [  3  38  77 140   0]]

Extracted first and last columns:
 [[[13  0]
  [14  0]
  [ 0  0]
  [43 46]]

 [[ 0  0]
  [ 0 45]
  [ 0 32]
  [31  2]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]
  [ 3  0]]]
