In [ ]:
import numpy as np
arr_zeros = np.zeros(5)
print(arr_zeros)
#creates 1d array of 5 elements all initialized to 0

[0. 0. 0. 0. 0.]


In [3]:
arr_empty = np.empty(4)
print(arr_empty)

[2.12199579e-314 4.67296746e-307 5.86949987e-321 8.93360228e-312]


In [4]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])   
print(arr[-1])  

10
50


In [ ]:
arr = np.array([0, 2, 3, 4, 5])
print(arr[1:4])  
print(arr[:3])   
print(arr[2:])   
print(arr[:])   
print(arr[::2])

In [5]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])
print(arr1 + arr2)
print(arr2 - arr1)
print(arr1 * arr2)
print(arr2 / arr1)
print(arr1 ** 2)
print(arr2 % arr1)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[ 1  4  9 16 25]
[0 0 0 0 0]


In [6]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([5, 20, 35])
print(arr1 == arr2)
print(arr1 > arr2)
print(arr1 < arr2)

[False  True False]
[ True False False]
[False False  True]


In [7]:
arr = np.array([1, 2, 3, 4, 5])
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())
print("Minimum:", arr.min())
print("Maximum:", arr.max())
print("Product:", arr.prod())

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951
Minimum: 1
Maximum: 5
Product: 120


Reshaping - changes the shape of an array ie 1D array can be reshaped into 2D array

In [12]:
arr_1d = np.array([1, 2, 3, 4])
reshape_row = arr_1d.reshape(1, 4)
print( reshape_row)

[[1 2 3 4]]


In [13]:
arr_1d = np.array([1, 2, 3, 4])
reshape_col = arr_1d.reshape(4,1)
print( reshape_col)

[[1]
 [2]
 [3]
 [4]]


In [16]:
arr= np.arange(1, 7) 
matrix = arr.reshape(2, 3) 
print(matrix)

[[1 2 3]
 [4 5 6]]
