In [9]:
import numpy as np

text = 'SUNITA'
print(np.char.lower(text))



sunita


In [15]:
print(np.char.add('Good ', 'Morning'))


Good Morning


In [10]:
import numpy as np

text = 'sunita'
print(np.char.upper(text))

SUNITA


In [11]:
text = 'python programming'
print(np.char.capitalize(text))

Python programming


In [12]:
text = '   hello   '
print(np.char.strip(text))


hello


In [13]:
text = 'hello world'
print(np.char.split(text))


['hello', 'world']


In [14]:
text = 'sunita'
print(np.char.count(text, 'a'))



1


In [18]:
array=np.array((1,2,3,4,5))
boolean=array>3
print(array)
print(boolean)

[1 2 3 4 5]
[False False False  True  True]


In [20]:
num=np.array([1,2,3,4,5,6,7,8,9,10])
num_copy=num.copy()
print(num_copy)
num_copy[num%2==0]=True
print(num_copy)

[ 1  2  3  4  5  6  7  8  9 10]
[1 1 3 1 5 1 7 1 9 1]


In [21]:
num=np.array([1,2,3,4,5,6,7,8,9,10])
num_copy=num.copy()
print(num_copy)
num_copy[num%2==0]=False
print(num_copy)

[ 1  2  3  4  5  6  7  8  9 10]
[1 0 3 0 5 0 7 0 9 0]


In [22]:
a1=np.array([1,2])
a2=np.array([3,4])
print(a1+a2)

[4 6]


interview=homogeneous shape and non homogeneous shapes of an array

In [23]:
#fancy indexing=multiple array lai access garxa
import numpy as np
arr=np.array([1,2,3])
select=arr[[0,1]]
print(select)

[1 2]


In [25]:
array=np.array(
  [
    [1,2,3],
    [4,5,6]
  ]
)
print(array)

[[1 2 3]
 [4 5 6]]


In [27]:
arr=np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,0,1,2]
])
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]


3d array

In [32]:
array1 = np.array([
  [[1, 2, 3],
   [4, 5, 6]
  ],
  [[7, 8, 9],
   [2, 4, 5]
  ],
  [[1, 2, 3],
   [4, 4, 6]
  ]
])

print(array1)


[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 4 5]]

 [[1 2 3]
  [4 4 6]]]


In [2]:
import numpy as np
arr=np.array(
  [
    [3,4],[5,6]
  ]
)
scalar=3
result=arr*scalar
result

array([[ 9, 12],
       [15, 18]])

In [4]:
a=np.array([[1,2,3],[5,6,7]])
b=np.array([10,20,30])
c=a+b
c

array([[11, 22, 33],
       [15, 26, 37]])

In [7]:
import numpy as np
arr=np.random.randint(10,10,size=(2,5,5))
[arr>50]=-1
print(arr)


SyntaxError: cannot assign to comparison (3331460329.py, line 3)